name: hirudorax
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2 

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- State Management (Riverpod) ---
  flutter_riverpod: ^2.5.1 
  riverpod_annotation: ^2.3.5 

  # --- Firebase Core & Services ---
  firebase_core: ^3.14.0      # Versi stabil terbaru
  firebase_database: ^11.0.0 # Versi stabil terbaru
  firebase_auth: ^5.1.0      # Versi stabil terbaru
  firebase_analytics: ^11.5.0 # Versi stabil terbaru
  
  # cloud_firestore: ^5.1.0 

  # firebase_messaging: ^15.0.0 
  flutter_slidable: ^3.1.0 
  glassmorphism: ^3.0.0            
  flutter_animate: ^4.3.0
  lottie: ^3.1.0                    # Versi lebih baru (cek pub.dev)
  flutter_staggered_animations: ^1.1.1

  # --- Navigation ---
  go_router: ^14.0.0 

  # --- Local Storage ---
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # --- Date & Time ---
  intl: ^0.19.0
  table_calendar: ^3.0.9

  # --- Charts & Data Visualization ---
  fl_chart: ^0.68.0              
  syncfusion_flutter_charts: ^26.1.35 
  # --- Utils & Code Generation Helper ---
  uuid: ^4.4.0                      
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1       
  json_annotation: ^4.9.0         
  collection: ^1.18.0 
  # --- Icons & Fonts ---
  iconsax: ^0.0.8

  google_fonts: ^6.2.1
  firebase_performance: ^0.10.1+7
  supabase_flutter: ^2.9.1
  dartz: ^0.10.1
  simple_animations: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 
  
  # --- Code Generation (Untuk Riverpod, Freezed, JSON Serialization, Hive) ---
  build_runner: ^2.4.9        # Versi stabil terbaru
  riverpod_generator: ^2.4.0  # Versi stabil terbaru
  freezed: ^2.5.2             # Versi stabil terbaru
  json_serializable: ^6.8.0   # Versi stabil terbaru
  hive_generator: ^2.0.1      # Versi stabil terbaru

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/lottie_animations/
  
  # fonts:
  #   - family: YourCustomFont
  #     fonts:
  #       - asset: assets/fonts/YourCustomFont-Regular.ttf
  #       - asset: assets/fonts/YourCustomFont-Bold.ttf
  #         weight: 700