// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg73BNMXHb0cDqB4icXdHzTSLO52st4rM',
    appId: '1:388605479107:web:cef4507a305f23629a7a76',
    messagingSenderId: '388605479107',
    projectId: 'hirudoraxriver',
    authDomain: 'hirudoraxriver.firebaseapp.com',
    databaseURL: 'https://hirudoraxriver-default-rtdb.firebaseio.com',
    storageBucket: 'hirudoraxriver.firebasestorage.app',
    measurementId: 'G-0HNHXPQDYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsxyMvjP5NWUdiMG0n0eFqLS8BO3stkoM',
    appId: '1:388605479107:android:a4e55bf161be18689a7a76',
    messagingSenderId: '388605479107',
    projectId: 'hirudoraxriver',
    databaseURL: 'https://hirudoraxriver-default-rtdb.firebaseio.com',
    storageBucket: 'hirudoraxriver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX6m8UJDwdtmbf1dlDDJ5yAflcx2tHRN8',
    appId: '1:388605479107:ios:8176b5749acace509a7a76',
    messagingSenderId: '388605479107',
    projectId: 'hirudoraxriver',
    databaseURL: 'https://hirudoraxriver-default-rtdb.firebaseio.com',
    storageBucket: 'hirudoraxriver.firebasestorage.app',
    iosBundleId: 'com.example.hirudorax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX6m8UJDwdtmbf1dlDDJ5yAflcx2tHRN8',
    appId: '1:388605479107:ios:8176b5749acace509a7a76',
    messagingSenderId: '388605479107',
    projectId: 'hirudoraxriver',
    databaseURL: 'https://hirudoraxriver-default-rtdb.firebaseio.com',
    storageBucket: 'hirudoraxriver.firebasestorage.app',
    iosBundleId: 'com.example.hirudorax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg73BNMXHb0cDqB4icXdHzTSLO52st4rM',
    appId: '1:388605479107:web:79acc3588f2d93c29a7a76',
    messagingSenderId: '388605479107',
    projectId: 'hirudoraxriver',
    authDomain: 'hirudoraxriver.firebaseapp.com',
    databaseURL: 'https://hirudoraxriver-default-rtdb.firebaseio.com',
    storageBucket: 'hirudoraxriver.firebasestorage.app',
    measurementId: 'G-B07VKWQY0B',
  );

}